import businessdecisionimpactdetermination from './business-decision-impact-determination.skill.json';
import federalandstateauditsmanagement from './federal-and-state-audits-management.skill.json';
import federalandstateauditcommunications from './federal-and-state-audit-communications.skill.json';
import performtaxpreparation from './perform-tax-preparation.skill.json';
import taxaccountingreportstrainingfacilitation from './tax-accounting-reports-training-facilitation.skill.json';
import taxdocumentationpoliciescompliance from './tax-documentation-policies-compliance.skill.json';
import taxissuesresolution from './tax-issues-resolution.skill.json';
import taxliabilitiesscrutiny from './tax-liabilities-scrutiny.skill.json';
import taxregulationschanges from './tax-regulations-changes.skill.json';
