import streamlineprocessesbyusingtimeeffectively from './streamline-processes-by-using-time-effectively.skill.json';
import developacompressiveplanformanagingtime from './develop-a-compressive-plan-for-managing-time.skill.json';
import assesstimemanagementpractices from './assess-time-management-practices.skill.json';
import maketimemanagementapriority from './make-time-management-a-priority.skill.json';
import applytimemanagementtechniques from './apply-time-management-techniques.skill.json';
import effortsprioritization from './efforts-prioritization.skill.json';
import processesstreamlining from './processes-streamlining.skill.json';
import staffworkloadsanalysis from './staff-workloads-analysis.skill.json';
import staffworkloadsprioritization from './staff-workloads-prioritization.skill.json';
