import taxdataanalysis from './tax-data-analysis.skill.json';
import taxresearch from './tax-research.skill.json';
import taxdevelopmentsmonitoring from './tax-developments-monitoring.skill.json';
import taxinformationresearch from './tax-information-research.skill.json';
import taxissuesidentification from './tax-issues-identification.skill.json';
import taxregulationsinterpretation from './tax-regulations-interpretation.skill.json';
import financialplanningguidance from './financial-planning-guidance.skill.json';
import taxreportspreparation from './tax-reports-preparation.skill.json';
import taxresearchschemesdevelopment from './tax-research-schemes-development.skill.json';
