import accountingtrendanalysis from './accounting-trend-analysis.skill.json';
import companywideplandevelopment from './company-wide-plan-development.skill.json';
import financialstatementreview from './financial-statement-review.skill.json';
import companywideplanimplementation from './company-wide-plan-implementation.skill.json';
import generallyacceptedaccountingprinciplesgaapmethodologyreview from './generally-accepted-accounting-principles-gaap-methodology-review.skill.json';
import generallyacceptedaccountingprinciplesgaapmethodologyimplementation from './generally-accepted-accounting-principles-gaap-methodology-implementation.skill.json';
import generallyacceptedaccountingprinciplesgaapmethodologyenforcement from './generally-accepted-accounting-principles-gaap-methodology-enforcement.skill.json';
import accountingmethodandpolicyimplementation from './accounting-method-and-policy-implementation.skill.json';
import accountingmethodandpolicyenforcement from './accounting-method-and-policy-enforcement.skill.json';
