import compileddataanalysis from './compiled-data-analysis.skill.json';
import tacticalandstrategicapproachesrecommendation from './tactical-and-strategic-approaches-recommendation.skill.json';
import trendsandinnovationsassessment from './trends-and-innovations-assessment.skill.json';
import trendsandinnovationsmonitoring from './trends-and-innovations-monitoring.skill.json';
import datareporting from './data-reporting.skill.json';
import estimatingtechniquesselection from './estimating-techniques-selection.skill.json';
import forecastmodelapplication from './forecast-model-application.skill.json';
import forecastingassumptionsvalidation from './forecasting-assumptions-validation.skill.json';
import forecastingtrendsidentification from './forecasting-trends-identification.skill.json';
