import ensurepresentationconsistency from './ensure-presentation-consistency.skill.json';
import presentationpreparation from './presentation-preparation.skill.json';
import presentationsdeliveryrehearsal from './presentations-delivery-rehearsal.skill.json';
import presentationstimingrehearsal from './presentations-timing-rehearsal.skill.json';
import targetedpresentationdelivery from './targeted-presentation-delivery.skill.json';
import virtualaudiencepresentationdelivery from './virtual-audience-presentation-delivery.skill.json';
import presentationissuesresolution from './presentation-issues-resolution.skill.json';
import researchfindingscommunication from './research-findings-communication.skill.json';
import visualcontentcreation from './visual-content-creation.skill.json';
