import auditfindingscommunication from './audit-findings-communication.skill.json';
import conductriskaudits from './conduct-risk-audits.skill.json';
import financialdatareporting from './financial-data-reporting.skill.json';
import sarbanesoxleyactsoxcompliancedetermination from './sarbanes-oxley-act-sox-compliance-determination.skill.json';
import auditreportwriting from './audit-report-writing.skill.json';
import financialstatementgenerallyacceptedaccountingprinciplesgaapcompliancereview from './financial-statement-generally-accepted-accounting-principles-gaap-compliance-review.skill.json';
import reconciliationauditing from './reconciliation-auditing.skill.json';
import financialstatementsconsolidation from './financial-statements-consolidation.skill.json';
import generallyacceptedauditingstandardsgaascompliance from './generally-accepted-auditing-standards-gaas-compliance.skill.json';
