import customerconcernescalation from './customer-concern-escalation.skill.json';
import customerinteractions from './customer-interactions.skill.json';
import customerservicebudgeting from './customer-service-budgeting.skill.json';
import customerserviceprotocoldesign from './customer-service-protocol-design.skill.json';
import customerserviceprotocolimplementation from './customer-service-protocol-implementation.skill.json';
import customerserviceresponsemetricsmonitoring from './customer-service-response-metrics-monitoring.skill.json';
import recruitingandtrainingprocedures from './recruiting-and-training-procedures.skill.json';
import serviceagreementlevelcompliance from './service-agreement-level-compliance.skill.json';
import staffingandtrainingneedsforecasting from './staffing-and-training-needs-forecasting.skill.json';
