import doubleentryaccountingoperation from './double-entry-accounting-operation.skill.json';
import journalentrycreation from './journal-entry-creation.skill.json';
import generalledgerinformationrecording from './general-ledger-information-recording.skill.json';
import financialstatementcreation from './financial-statement-creation.skill.json';
import transactionrecord from './transaction-record.skill.json';
import complianceadvice from './compliance-advice.skill.json';
import complianceevaluation from './compliance-evaluation.skill.json';
import controlimplementation from './control-implementation.skill.json';
import systemmanagement from './system-management.skill.json';
