import cashflowforecasting from './cash-flow-forecasting.skill.json';
import financialplananalysis from './financial-plan-analysis.skill.json';
import taxestimatesmonitoring from './tax-estimates-monitoring.skill.json';
import taxestimatesreview from './tax-estimates-review.skill.json';
import taxinformationsummarization from './tax-information-summarization.skill.json';
import taxissuescommunication from './tax-issues-communication.skill.json';
import taxplanningapproachesdesign from './tax-planning-approaches-design.skill.json';
import taxplanningtaxreportspreparation from './tax-planning-tax-reports-preparation.skill.json';
import taxreturnsreview from './tax-returns-review.skill.json';
